from centos:centos7
USER root
ADD nginx-1.14.2.tar.gz /opt
ADD ngx_http_proxy_connect_module-master.zip /opt
RUN set -xe \ 
&& cd /opt \
&& ls -al \
&& yum install -y make openssl-devel gcc patch pcre pcre-devel unzip wget vim curl \
&& unzip ngx_http_proxy_connect_module-master.zip \
&& mv ngx_http_proxy_connect_module-master ngx_http_proxy_connect_module \
&& mv ngx_http_proxy_connect_module nginx-1.14.2 \
&& cd nginx-1.14.2 \
&& patch -p1 < ngx_http_proxy_connect_module/patch/proxy_connect_1014.patch \
&& ./configure --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --add-module=ngx_http_proxy_connect_module \
&& make && make install \
&& ln -s /usr/local/nginx/sbin/nginx /usr/local/bin/nginx \
&& mkdir -p /usr/local/nginx/conf/conf.d/ 
ADD nginx.conf /usr/local/nginx/conf/
ADD forward.conf /usr/local/nginx/conf/conf.d/
EXPOSE 888
CMD ["nginx", "-g", "daemon off;"]
